FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 10000

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["WebZOO.API.csproj", "./"]
RUN dotnet restore "WebZOO.API.csproj" 
COPY . .
RUN dotnet build "WebZOO.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "WebZOO.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "WebZOO.API.dll"]